### PR TITLE
Fix for recent youtube change

### PR DESCRIPTION
**Pull request by vinnyrose**
fmt_url_map was removed by youtube which lead to videos not loading, using a different property to get the format list.

### CODE REVIEW

**Comment by vinnyrose** [comment]
Should get this one in as soon as possible. And probably need a version change on this as well.

**Comment by asoksevil** [comment]
Hope Connor can see this and fix it ASAP.

**Comment by vinnyrose** [comment]
this is not working on embedded youtube videos. Vimeo videos seem fine. Researching why now and will commit a change to this request.

**Comment by greneholt** [comment]
Thanks for the fix! I'll have a new version online in a few minutes.

**Pull request closed without merging**
