### PR TITLE
Fix YouTube for users without Flash installed

### PR DESCRIPTION
**Pull request by dlh**
This change breaks the "Use original player" action, so I don't really expect it to be merged.

I'll try to take a look at fixing that, but feel free to tackle it yourself.

Issue #32 is related.

### CODE REVIEW

**Comment by dlh** [comment]
Actually, this still has issues: the youtube HTML5 player for some videos will load (but it is in the hidden div), and it autoplays.

**Comment by dlh** [comment]
I've blocked the loading of the (autoplaying) html5 player. However, the “Use original player” action is still broken.

Still, this solution is rather hacky…

**Comment by ggustafsson** [comment]
I tried it but it doesn't work. I just double-clicked on the safariextz file. Need a fix so bad :'(

**Comment by ylor** [comment]
If you turn off auto-play YouTube videos in the extension settings it cleared up the issue for me.

**Comment by greneholt** [comment]
Thanks for this code, but I have chosen to fix the issue in a slightly more hackish, but more reliable way. Sorry its taken so long.

**Pull request closed without merging**
