### PR TITLE
Start time feature

### PR DESCRIPTION
**Pull request by dlh**
I added support for YouTube's `start`/`t`/`time` URL parameters, and the `#t=` hash syntax.

### CODE REVIEW

**Comment by riddle** [comment]
I’d love to see it working. Greneholt, can you please pull the code? It’s like linking to #hash for text content, very useful. I still have to open Chrome to test my `#t=` links when I share parts of YouTube videos with my friends.

**Comment by vpieter** [comment]
I've been watching this thread for a while now, and I'll join in saying that to me it's the biggest annoyance with this otherwise excellent extension. When I click a link to a referencing video I often have to go looking for the right minute/second part to see what is being referred to.

**Comment by greneholt** [comment]
I apologize that I did not pull this a long time ago, but in the meantime YouTube5 has been majorly refactored and this change is out of sync. This is also the wrong place for this change to be made. It should be done in the player, not the loading code, so that clicking on links on a video page will jump to that point without reloading everything. I also don't like adding features to YouTube5 that only work on one site. There are ways this could be implemented that would support both YouTube and Vimeo.

For instance:
- When the player first starts playing, it checks the url hash of the current page and jumps to that time.
- The player adds an event listener to the document that watches for clicks on links in the form "(\d+:)?\d{1,2}:\d{2}". When one is clicked, it prevents the default action and jumps to the desired point in the video

If someone would like to make these changes and submit a new pull request, I'd be glad to review and merge it. But at the moment I don't have time to make these changes myself.

**Comment by greneholt** [comment]
Just wanted to let everyone know that YouTube5 v2.5.1 has full support for start times through link hashes, embeds, and even timecode links in comments.

**Comment by greneholt** [comment]
Thanks to dlh for some of the code included in the new version.

**Comment by vpieter** [comment]
Thanks so much to both of your for your time.

**Pull request closed without merging**
